//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecifierTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Const</string>
  <string>GlobalConfig</string>
  <string>Localized</string>
  <string>Transient</string>
  <string>DuplicateTransient</string>
  <string>NonPIETransient</string>
  <string>Ref</string>
  <string>Export</string>
  <string>EditInline</string>
  <string>NoClear</string>
  <string>EditFixedSize</string>
  <string>Replicated</string>
  <string>RepRetry</string>
  <string>NotReplicated</string>
  <string>Interp</string>
  <string>NonTransactional</string>
  <string>Instanced</string>
  <string>BlueprintAssignable</string>
  <string>SimpleDisplay</string>
  <string>AdvancedDisplay</string>
  <string>EditAnywhere</string>
  <string>EditInstanceOnly</string>
  <string>EditDefaultsOnly</string>
  <string>VisibleAnywhere</string>
  <string>VisibleInstanceOnly</string>
  <string>VisibleDefaultsOnly</string>
  <string>BlueprintReadOnly</string>
  <string>BlueprintReadWrite</string>
  <string>AssetRegistrySearchable</string>
  <string>SaveGame</string>
  <string>BlueprintCallable</string>
  <string>BlueprintAuthorityOnly</string>
  <string>TextExportTransient</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UPROPERTY_Specifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UPROPERTY_Specifiers"]));
            }
            set {
                this["UPROPERTY_Specifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>BlueprintType</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UENUM_Specifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UENUM_Specifiers"]));
            }
            set {
                this["UENUM_Specifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BlueprintAuthorityOnly</string>
  <string>BlueprintCallable</string>
  <string>BlueprintCosmetic</string>
  <string>BlueprintGetter</string>
  <string>BlueprintImplementableEvent</string>
  <string>BlueprintInternalUseOnly</string>
  <string>BlueprintNativeEvent</string>
  <string>BlueprintPure</string>
  <string>BlueprintSetter</string>
  <string>CallInEditor</string>
  <string>Client</string>
  <string>CustomThunk</string>
  <string>Exec</string>
  <string>NetMulticast</string>
  <string>Reliable</string>
  <string>SealedEvent</string>
  <string>ServiceRequest</string>
  <string>ServiceResponse</string>
  <string>Server</string>
  <string>Unreliable</string>
  <string>WithValidation</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UFUNCTION_Specifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UFUNCTION_Specifiers"]));
            }
            set {
                this["UFUNCTION_Specifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Atomic</string>
  <string>Blueprintable</string>
  <string>BlueprintType</string>
  <string>Immutable</string>
  <string>NoExport</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection USTRUCT_Specifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["USTRUCT_Specifiers"]));
            }
            set {
                this["USTRUCT_Specifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Abstract</string>
  <string>AdvancedClassDisplay</string>
  <string>Blueprintable</string>
  <string>BlueprintType</string>
  <string>CollapseCategories</string>
  <string>Const</string>
  <string>ConversionRoot</string>
  <string>CustomConstructor</string>
  <string>DefaultToInstanced</string>
  <string>Deprecated</string>
  <string>DontCollapseCategories</string>
  <string>EditInlineNew</string>
  <string>HideDropdown</string>
  <string>Intrinsic</string>
  <string>MinimalAPI</string>
  <string>NoExport</string>
  <string>NonTransient</string>
  <string>NotBlueprintable</string>
  <string>NotPlaceable</string>
  <string>PerObjectConfig</string>
  <string>Placeable</string>
  <string>Transient</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UCLASS_Specifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UCLASS_Specifiers"]));
            }
            set {
                this["UCLASS_Specifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>BlueprintType</string>\r\n  <string>MinimalAPI</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UINTERFACE_Specifiers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UINTERFACE_Specifiers"]));
            }
            set {
                this["UINTERFACE_Specifiers"] = value;
            }
        }
    }
}
